name: Json workflow

on:
  push:
    branches: [ pullstream-json ]
  pull_request:
    branches: [ pullstream-json ]
defaults:
  run:
    working-directory: ./src
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        json-net-version:
          - '9.0.1'
          - '10.0.1'
          - '11.0.1'
          - '12.0.1'
          - '13.0.1'
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103

    - name: Test
      run: 'dotnet test --configuration Debug --verbosity normal PullStream.Json.Tests /p:JsonNetVersion=${{ matrix.json-net-version }}'

  publish:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103

    - name: Publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ./src/PullStream.Json/PullStream.Json.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        TAG_COMMIT: true
        TAG_FORMAT: pullstream-json-v*
        NUGET_KEY: ${{secrets.NUGETKEY}}
        NUGET_SOURCE: https://api.nuget.org
        INCLUDE_SYMBOLS: true