name: PullStream workflow

on:
  push:
    branches: [ pullstream ]
  pull_request:
    branches: [ pullstream ]
defaults:
  run:
    working-directory: ./src
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
jobs:
  test-pullstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103

    - name: Test
      run: dotnet test --configuration Debug --verbosity normal PullStream.Tests

  publish-pullstream:
    runs-on: ubuntu-latest
    needs: test-core
    if: ${{ github.event_name == 'push' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.103

    - name: Publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ./src/PullStream/PullStream.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        TAG_COMMIT: true
        TAG_FORMAT: pullstream-v*
        NUGET_KEY: ${{secrets.NUGETKEY}}
        NUGET_SOURCE: https://api.nuget.org
        INCLUDE_SYMBOLS: true